
NETWORK_MODE = "wifi"

HOTSPOT_SSID = "Anthony"
HOTSPOT_PASSWORD = "anthonyy"
HOTSPOT_BACKEND_URL = "http://172.20.10.4:8000"

WIFI_SSID = "FN MIFI 24"
WIFI_PASSWORD = "parisparis"
WIFI_BACKEND_URL = "http://192.168.1.2:8000"

if NETWORK_MODE == "hotspot":
    SSID = HOTSPOT_SSID
    PASSWORD = HOTSPOT_PASSWORD
    BACKEND_URL = HOTSPOT_BACKEND_URL
else:
    SSID = WIFI_SSID
    PASSWORD = WIFI_PASSWORD
    BACKEND_URL = WIFI_BACKEND_URL

VOLUME = .5

VAD_FLOOR = 35
VAD_MULT = 2.5

SFX_BOOT = "/src/sfx/boot.wav"
SFX_BUTTON = "/src/sfx/button.wav"
SFX_PROCESSING = "/src/sfx/processing.wav"
SFX_THINKING = "/src/sfx/thinking.wav"
